name: tiny_cnn

channels:
  - conda-forge
  - anaconda
  - plotly

dependencies:
  - python=3.10.5
  - ipykernel
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - contextlib2
  - psutil
  - plotly #=5.11.0
  - black
  - papermill
  - prettytable
  - pip
  - pip:
    - tensorflow==2.10
    - tensorboard
    - tensorflow_datasets
    - tensorflow-model-optimization
    - tensorboard_plugin_profile
    # - jupyterlab_tensorboard
    - jupyterlab-code-formatter
    #- mlflow
    - pydot
    - wandb
    #- hydra-core
    #- deeplake #>=3.0.13
    - netron
    - silabs-mltk
    - split-folders
    - unrar
    - pyserial >=3.4
    - esptool >=3.3
    #- everywhereml

    #- line-profiler


